api_key="empty"
weather_api_key="c8b138cd625d476fbdb31921231507"
DEFAULT_LOCATION="empty"
UNIT="empty"
spotify_client_id="empty"
spotify_client_secret="empty"
HomeAssistant_URL_IP="empty"
HomeAssistant_Token="empty"